<?php

return [
    array('code' => 'AFN',
        'countryname' => 'Afghanistan',
        'name' => 'Afghanistan Afghani',
        'symbol' => '&#1547;',
        'prefix' => true,
    ),

    array('code' => 'ARS',
        'countryname' => 'Argentina',
        'name' => 'Argentine Peso',
        'symbol' => '&#36;',
        'prefix' => true,
    ),

    array('code' => 'AWG',
        'countryname' => 'Aruba',
        'name' => 'Aruban florin',
        'symbol' => '&#402;',
        'prefix' => true,
    ),

    array('code' => 'AUD',
        'countryname' => 'Australia',
        'name' => 'Australian Dollar',
        'symbol' => '&#65;&#36;',
        'prefix' => true,
    ),

    array('code' => 'AZN',
        'countryname' => 'Azerbaijan',
        'name' => 'Azerbaijani Manat',
        'symbol' => '&#8380;',
        'prefix' => true,
    ),

    array('code' => 'BSD',
        'countryname' => 'The Bahamas',
        'name' => 'Bahamas Dollar',
        'symbol' => '&#66;&#36;',
        'prefix' => true,
    ),

    array('code' => 'BBD',
        'countryname' => 'Barbados',
        'name' => 'Barbados Dollar',
        'symbol' => '&#66;&#100;&#115;&#36;',
        'prefix' => true,
    ),

    array('code' => 'BDT',
        'countryname' => 'People\'s Republic of Bangladesh',
        'name' => 'Bangladeshi taka',
        'symbol' => '&#2547;',
        'prefix' => true,
    ),

    array('code' => 'BYN',
        'countryname' => 'Belarus',
        'name' => 'Belarus Ruble',
        'symbol' => '&#66;&#114;',
        'prefix' => true,
    ),

    array('code' => 'BZD',
        'countryname' => 'Belize',
        'name' => 'Belize Dollar',
        'symbol' => '&#66;&#90;&#36;',
        'prefix' => true,
    ),

    array('code' => 'BMD',
        'countryname' => 'British Overseas Territory of Bermuda',
        'name' => 'Bermudian Dollar',
        'symbol' => '&#66;&#68;&#36;',
        'prefix' => true,
    ),

    array('code' => 'BOP',
        'countryname' => 'Bolivia',
        'name' => 'Boliviano',
        'symbol' => '&#66;&#115;',
        'prefix' => true,
    ),

    array('code' => 'BAM',
        'countryname' => 'Bosnia and Herzegovina',
        'name' => 'Bosnia-Herzegovina Convertible Marka',
        'symbol' => '&#75;&#77;',
        'prefix' => true,
    ),

    array('code' => 'BWP',
        'countryname' => 'Botswana',
        'name' => 'Botswana pula',
        'symbol' => '&#80;',
        'prefix' => true,
    ),

    array('code' => 'BGN',
        'countryname' => 'Bulgaria',
        'name' => 'Bulgarian lev',
        'symbol' => '&#1083;&#1074;',
        'prefix' => false,
    ),

    array('code' => 'BRL',
        'countryname' => 'Brazil',
        'name' => 'Brazilian real',
        'symbol' => '&#82;&#36;',
        'prefix' => true,
    ),

    array('code' => 'BND',
        'countryname' => 'Sultanate of Brunei',
        'name' => 'Brunei dollar',
        'symbol' => '&#66;&#36;',
        'prefix' => true,
    ),

    array('code' => 'KHR',
        'countryname' => 'Cambodia',
        'name' => 'Cambodian riel',
        'symbol' => '&#6107;',
        'prefix' => true,
    ),

    array('code' => 'CAD',
        'countryname' => 'Canada',
        'name' => 'Canadian dollar',
        'symbol' => '&#67;&#36;',
        'prefix' => true,
    ),

    array('code' => 'KYD',
        'countryname' => 'Cayman Islands',
        'name' => 'Cayman Islands dollar',
        'symbol' => '&#36;',
        'prefix' => true,
    ),

    array('code' => 'CLP',
        'countryname' => 'Chile',
        'name' => 'Chilean peso',
        'symbol' => '&#36;',
        'prefix' => true,
    ),

    array('code' => 'CNY',
        'countryname' => 'China',
        'name' => 'Chinese Yuan Renminbi',
        'symbol' => '&#165;',
        'prefix' => true,
    ),

    array('code' => 'COP',
        'countryname' => 'Colombia',
        'name' => 'Colombian peso',
        'symbol' => '&#36;',
        'prefix' => true,
    ),

    array('code' => 'CRC',
        'countryname' => 'Costa Rica',
        'name' => 'Costa Rican colón',
        'symbol' => '&#8353;',
        'prefix' => true,
    ),

    array('code' => 'HRK',
        'countryname' => 'Croatia',
        'name' => 'Croatian kuna',
        'symbol' => '&#107;&#110;',
        'prefix' => true,
    ),

    array('code' => 'CUP',
        'countryname' => 'Cuba',
        'name' => 'Cuban peso',
        'symbol' => '&#8369;',
        'prefix' => true,
    ),

    array('code' => 'CZK',
        'countryname' => 'Czech Republic',
        'name' => 'Czech koruna',
        'symbol' => '&#75;&#269;',
        'prefix' => true,
    ),

    array('code' => 'DKK',
        'countryname' => 'Denmark, Greenland, and the Faroe Islands',
        'name' => 'Danish krone',
        'symbol' => '&#107;&#114;',
        'prefix' => true,
    ),

    array('code' => 'DOP',
        'countryname' => 'Dominican Republic',
        'name' => 'Dominican peso',
        'symbol' => '&#82;&#68;&#36;',
        'prefix' => true,
    ),

    array('code' => 'XCD',
        'countryname' => 'Antigua and Barbuda, Commonwealth of Dominica, Grenada, Montserrat, St. Kitts and Nevis, Saint Lucia and St. Vincent and the Grenadines',
        'name' => 'Eastern Caribbean dollar',
        'symbol' => '&#36;',
        'prefix' => true,
    ),

    array('code' => 'EGP',
        'countryname' => 'Egypt',
        'name' => 'Egyptian pound',
        'symbol' => '&#163;',
        'prefix' => true,
    ),

    array('code' => 'SVC',
        'countryname' => 'El Salvador',
        'name' => 'Salvadoran colón',
        'symbol' => '&#36;',
        'prefix' => true,
    ),

    array('code' => 'EEK',
        'countryname' => 'Estonia',
        'name' => 'Estonian kroon',
        'symbol' => '&#75;&#114;',
        'prefix' => true,
    ),

    array('code' => 'EUR',
        'countryname' => 'European Union, Italy, Belgium, Croatia, Cyprus, Czechia, Denmark, Estonia, Finland, France, Germany,
                    Greece, Hungary, Ireland, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Poland,
                    Portugal, Romania, Slovakia, Slovenia, Spain, Sweden',
        'name' => 'Euro',
        'symbol' => '&#8364;',
        'prefix' => true,
    ),

    array('code' => 'FKP',
        'countryname' => 'Falkland Islands',
        'name' => 'Falkland Islands (Malvinas) Pound',
        'symbol' => '&#70;&#75;&#163;',
        'prefix' => true,
    ),

    array('code' => 'FJD',
        'countryname' => 'Fiji',
        'name' => 'Fijian dollar',
        'symbol' => '&#70;&#74;&#36;',
        'prefix' => true,
    ),

    array('code' => 'GHC',
        'countryname' => 'Ghana',
        'name' => 'Ghanaian cedi',
        'symbol' => '&#71;&#72;&#162;',
        'prefix' => true,
    ),

    array('code' => 'GIP',
        'countryname' => 'Gibraltar',
        'name' => 'Gibraltar pound',
        'symbol' => '&#163;',
        'prefix' => true,
    ),

    array('code' => 'GTQ',
        'countryname' => 'Guatemala',
        'name' => 'Guatemalan quetzal',
        'symbol' => '&#81;',
        'prefix' => true,
    ),

    array('code' => 'GGP',
        'countryname' => 'Guernsey',
        'name' => 'Guernsey pound',
        'symbol' => '&#81;',
        'prefix' => true,
    ),

    array('code' => 'GYD',
        'countryname' => 'Guyana',
        'name' => 'Guyanese dollar',
        'symbol' => '&#71;&#89;&#36;',
        'prefix' => true,
    ),

    array('code' => 'HNL',
        'countryname' => 'Honduras',
        'name' => 'Honduran lempira',
        'symbol' => '&#76;',
        'prefix' => true,
    ),

    array('code' => 'HKD',
        'countryname' => 'Hong Kong',
        'name' => 'Hong Kong dollar',
        'symbol' => '&#72;&#75;&#36;',
        'prefix' => true,
    ),

    array('code' => 'HUF',
        'countryname' => 'Hungary',
        'name' => 'Hungarian forint',
        'symbol' => '&#70;&#116;',
        'prefix' => true,
    ),

    array('code' => 'ISK',
        'countryname' => 'Iceland',
        'name' => 'Icelandic króna',
        'symbol' => '&#237;&#107;&#114;',
        'prefix' => true,
    ),

    array('code' => 'INR',
        'countryname' => 'India',
        'name' => 'Indian rupee',
        'symbol' => '&#8377;',
        'prefix' => true,
    ),

    array('code' => 'IDR',
        'countryname' => 'Indonesia',
        'name' => 'Indonesian rupiah',
        'symbol' => '&#82;&#112;',
        'prefix' => true,
    ),

    array('code' => 'IRR',
        'countryname' => 'Iran',
        'name' => 'Iranian rial',
        'symbol' => '&#65020;',
        'prefix' => true,
    ),

    array('code' => 'IMP',
        'countryname' => 'Isle of Man',
        'name' => 'Manx pound',
        'symbol' => '&#163;',
        'prefix' => true,
    ),

    array('code' => 'ILS',
        'countryname' => 'Israel, Palestinian territories of the West Bank and the Gaza Strip',
        'name' => 'Israeli Shekel',
        'symbol' => '&#8362;',
        'prefix' => true,
    ),

    array('code' => 'JMD',
        'countryname' => 'Jamaica',
        'name' => 'Jamaican dollar',
        'symbol' => '&#74;&#36;',
        'prefix' => true,
    ),

    array('code' => 'JPY',
        'countryname' => 'Japan',
        'name' => 'Japanese yen',
        'symbol' => '&#165;',
        'prefix' => true,
    ),

    array('code' => 'JEP',
        'countryname' => 'Jersey',
        'name' => 'Jersey pound',
        'symbol' => '&#163;',
        'prefix' => true,
    ),

    array('code' => 'KZT',
        'countryname' => 'Kazakhstan',
        'name' => 'Kazakhstani tenge',
        'symbol' => '&#8376;',
        'prefix' => true,
    ),

    array('code' => 'KPW',
        'countryname' => 'North Korea',
        'name' => 'North Korean won',
        'symbol' => '&#8361;',
        'prefix' => true,
    ),

    array('code' => 'KPW',
        'countryname' => 'South Korea',
        'name' => 'South Korean won',
        'symbol' => '&#8361;',
        'prefix' => true,
    ),

    array('code' => 'KGS',
        'countryname' => 'Kyrgyz Republic',
        'name' => 'Kyrgyzstani som',
        'symbol' => '&#1083;&#1074;',
        'prefix' => true,
    ),

    array('code' => 'LAK',
        'countryname' => 'Laos',
        'name' => 'Lao kip',
        'symbol' => '&#8365;',
        'prefix' => true,
    ),

    array('code' => 'LAK',
        'countryname' => 'Laos',
        'name' => 'Latvian lats',
        'symbol' => '&#8364;',
        'prefix' => true,
    ),

    array('code' => 'LVL',
        'countryname' => 'Laos',
        'name' => 'Latvian lats',
        'symbol' => '&#8364;',
        'prefix' => true,
    ),

    array('code' => 'LBP',
        'countryname' => 'Lebanon',
        'name' => 'Lebanese pound',
        'symbol' => '&#76;&#163;',
        'prefix' => true,
    ),

    array('code' => 'LRD',
        'countryname' => 'Liberia',
        'name' => 'Liberian dollar',
        'symbol' => '&#76;&#68;&#36;',
        'prefix' => true,
    ),

    array('code' => 'LTL',
        'countryname' => 'Lithuania',
        'name' => 'Lithuanian litas',
        'symbol' => '&#8364;',
        'prefix' => true,
    ),

    array('code' => 'MKD',
        'countryname' => 'North Macedonia',
        'name' => 'Macedonian denar',
        'symbol' => '&#1076;&#1077;&#1085;',
        'prefix' => true,
    ),

    array('code' => 'MYR',
        'countryname' => 'Malaysia',
        'name' => 'Malaysian ringgit',
        'symbol' => '&#82;&#77;',
        'prefix' => true,
    ),

    array('code' => 'MUR',
        'countryname' => 'Mauritius',
        'name' => 'Mauritian rupee',
        'symbol' => '&#82;&#115;',
        'prefix' => true,
    ),

    array('code' => 'MXN',
        'countryname' => 'Mexico',
        'name' => 'Mexican peso',
        'symbol' => '&#77;&#101;&#120;&#36;',
        'prefix' => true,
    ),

    array('code' => 'MNT',
        'countryname' => 'Mongolia',
        'name' => 'Mongolian tögrög',
        'symbol' => '&#8366;',
        'prefix' => true,
    ),


    array('code' => 'MZN',
        'countryname' => 'Mozambique',
        'name' => 'Mozambican metical',
        'symbol' => '&#77;&#84;',
        'prefix' => true,
    ),

    array('code' => 'NAD',
        'countryname' => 'Namibia',
        'name' => 'Namibian dollar',
        'symbol' => '&#78;&#36;',
        'prefix' => true,
    ),

    array('code' => 'NPR',
        'countryname' => 'Federal Democratic Republic of Nepal',
        'name' => 'Nepalese rupee',
        'symbol' => '&#82;&#115;&#46;',
        'prefix' => true,
    ),

    array('code' => 'ANG',
        'countryname' => 'Curaçao and Sint Maarten',
        'name' => 'Netherlands Antillean guilder',
        'symbol' => '&#402;',
        'prefix' => true,
    ),

    array('code' => 'NZD',
        'countryname' => 'New Zealand, the Cook Islands, Niue, the Ross Dependency, Tokelau, the Pitcairn Islands',
        'name' => 'New Zealand dollar',
        'symbol' => '&#36;',
        'prefix' => true,
    ),


    array('code' => 'NIO',
        'countryname' => 'Nicaragua',
        'name' => 'Nicaraguan córdoba',
        'symbol' => '&#67;&#36;',
        'prefix' => true,
    ),

    array('code' => 'NGN',
        'countryname' => 'Nigeria',
        'name' => 'Nigerian naira',
        'symbol' => '&#8358;',
        'prefix' => true,
    ),

    array('code' => 'NOK',
        'countryname' => 'Norway and its dependent territories',
        'name' => 'Norwegian krone',
        'symbol' => '&#107;&#114;',
        'prefix' => true,
    ),

    array('code' => 'OMR',
        'countryname' => 'Oman',
        'name' => 'Omani rial',
        'symbol' => '&#65020;',
        'prefix' => true,
    ),

    array('code' => 'PKR',
        'countryname' => 'Pakistan',
        'name' => 'Pakistani rupee',
        'symbol' => '&#82;&#115;',
        'prefix' => true,
    ),

    array('code' => 'PAB',
        'countryname' => 'Panama',
        'name' => 'Panamanian balboa',
        'symbol' => '&#66;&#47;&#46;',
        'prefix' => true,
    ),

    array('code' => 'PYG',
        'countryname' => 'Paraguay',
        'name' => 'Paraguayan Guaraní',
        'symbol' => '&#8370;',
        'prefix' => true,
    ),

    array('code' => 'PEN',
        'countryname' => 'Peru',
        'name' => 'Sol',
        'symbol' => '&#83;&#47;&#46;',
        'prefix' => true,
    ),

    array('code' => 'PHP',
        'countryname' => 'Philippines',
        'name' => 'Philippine peso',
        'symbol' => '&#8369;',
        'prefix' => true,
    ),

    array('code' => 'PLN',
        'countryname' => 'Poland',
        'name' => 'Polish złoty',
        'symbol' => '&#122;&#322;',
        'prefix' => true,
    ),

    array('code' => 'QAR',
        'countryname' => 'State of Qatar',
        'name' => 'Qatari Riyal',
        'symbol' => '&#65020;',
        'prefix' => true,
    ),

    array('code' => 'RON',
        'countryname' => 'Romania',
        'name' => 'Romanian leu (Leu românesc)',
        'symbol' => '&#76;',
        'prefix' => true,
    ),

    array('code' => 'RUB',
        'countryname' => 'Russian Federation, Abkhazia and South Ossetia, Donetsk and Luhansk',
        'name' => 'Russian ruble',
        'symbol' => '&#8381;',
        'prefix' => true,
    ),


    array('code' => 'SHP',
        'countryname' => 'Saint Helena, Ascension and Tristan da Cunha',
        'name' => 'Saint Helena pound',
        'symbol' => '&#163;',
        'prefix' => true,
    ),

    array('code' => 'SAR',
        'countryname' => 'Saudi Arabia',
        'name' => 'Saudi riyal',
        'symbol' => '&#65020;',
        'prefix' => true,
    ),

    array('code' => 'RSD',
        'countryname' => 'Serbia',
        'name' => 'Serbian dinar',
        'symbol' => '&#100;&#105;&#110;',
        'prefix' => true,
    ),

    array('code' => 'SCR',
        'countryname' => 'Seychelles',
        'name' => 'Seychellois rupee',
        'symbol' => '&#82;&#115;',
        'prefix' => true,
    ),

    array('code' => 'SGD',
        'countryname' => 'Singapore',
        'name' => 'Singapore dollar',
        'symbol' => '&#83;&#36;',
        'prefix' => true,
    ),

    array('code' => 'SBD',
        'countryname' => 'Solomon Islands',
        'name' => 'Solomon Islands dollar',
        'symbol' => '&#83;&#73;&#36;',
        'prefix' => true,
    ),

    array('code' => 'SOS',
        'countryname' => 'Somalia',
        'name' => 'Somali shilling',
        'symbol' => '&#83;&#104;&#46;&#83;&#111;',
        'prefix' => true,
    ),

    array('code' => 'ZAR',
        'countryname' => 'South Africa',
        'name' => 'South African rand',
        'symbol' => '&#82;',
        'prefix' => true,
    ),

    array('code' => 'LKR',
        'countryname' => 'Sri Lanka',
        'name' => 'Sri Lankan rupee',
        'symbol' => '&#82;&#115;',
        'prefix' => true,
    ),


    array('code' => 'SEK',
        'countryname' => 'Sweden',
        'name' => 'Swedish krona',
        'symbol' => '&#107;&#114;',
        'prefix' => true,
    ),


    array('code' => 'CHF',
        'countryname' => 'Switzerland',
        'name' => 'Swiss franc',
        'symbol' => '&#67;&#72;&#102;',
        'prefix' => true,
    ),

    array('code' => 'SRD',
        'countryname' => 'Suriname',
        'name' => 'Suriname Dollar',
        'symbol' => '&#83;&#114;&#36;',
        'prefix' => true,
    ),

    array('code' => 'SYP',
        'countryname' => 'Syria',
        'name' => 'Syrian pound',
        'symbol' => '&#163;&#83;',
        'prefix' => true,
    ),

    array('code' => 'TWD',
        'countryname' => 'Taiwan',
        'name' => 'New Taiwan dollar',
        'symbol' => '&#78;&#84;&#36;',
        'prefix' => true,
    ),


    array('code' => 'THB',
        'countryname' => 'Thailand',
        'name' => 'Thai baht',
        'symbol' => '&#3647;',
        'prefix' => true,
    ),


    array('code' => 'TTD',
        'countryname' => 'Trinidad and Tobago',
        'name' => 'Trinidad and Tobago dollar',
        'symbol' => '&#84;&#84;&#36;',
        'prefix' => true,
    ),


    array('code' => 'TRY',
        'countryname' => 'Turkey, Turkish Republic of Northern Cyprus',
        'name' => 'Turkey Lira',
        'symbol' => '&#8378;',
        'prefix' => true,
    ),

    array('code' => 'TVD',
        'countryname' => 'Tuvalu',
        'name' => 'Tuvaluan dollar',
        'symbol' => '&#84;&#86;&#36;',
        'prefix' => true,
    ),

    array('code' => 'UAH',
        'countryname' => 'Ukraine',
        'name' => 'Ukrainian hryvnia',
        'symbol' => '&#8372;',
        'prefix' => true,
    ),


    array('code' => 'GBP',
        'countryname' => 'United Kingdom, Jersey, Guernsey, the Isle of Man, Gibraltar, South Georgia and the South Sandwich Islands, the British Antarctic Territory, and Tristan da Cunha',
        'name' => 'Pound sterling',
        'symbol' => '&#163;',
        'prefix' => true,
    ),


    array('code' => 'UGX',
        'countryname' => 'Uganda',
        'name' => 'Ugandan shilling',
        'symbol' => '&#85;&#83;&#104;',
        'prefix' => true,
    ),


    array('code' => 'USD',
        'countryname' => 'United States',
        'name' => 'United States dollar',
        'symbol' => '&#36;',
        'prefix' => true,
    ),

    array('code' => 'UYU',
        'countryname' => 'Uruguayan',
        'name' => 'Peso Uruguayolar',
        'symbol' => '&#36;&#85;',
        'prefix' => true,
    ),

    array('code' => 'UZS',
        'countryname' => 'Uzbekistan',
        'name' => 'Uzbekistani soʻm',
        'symbol' => '&#1083;&#1074;',
        'prefix' => true,
    ),


    array('code' => 'VEF',
        'countryname' => 'Venezuela',
        'name' => 'Venezuelan bolívar',
        'symbol' => '&#66;&#115;',
        'prefix' => true,
    ),


    array('code' => 'VND',
        'countryname' => 'Vietnam',
        'name' => 'Vietnamese dong (Đồng)',
        'symbol' => '&#8363;',
        'prefix' => true,
    ),

    array('code' => 'VND',
        'countryname' => 'Yemen',
        'name' => 'Yemeni rial',
        'symbol' => '&#65020;',
        'prefix' => true,
    ),

    array('code' => 'ZWD',
        'countryname' => 'Zimbabwe',
        'name' => 'Zimbabwean dollar',
        'symbol' => '&#90;&#36;',
        'prefix' => true,
    ),
];
